### ISSUE TITLE
Local Environment Setup Issue

### ISSUE THREAD

**Issue by Renilneopraxis** [bigcommerce/b2b-buyer-portal#11]
Hi Team,

We are facing issue to setup the local development environment. 

We are trying to see the b2b buyer portal host 3001 on Stencil local host 3000. It worked initially but started giving issues later.. It shows the loading screen for a while and then gives below error screen.

<img width="1172" alt="Screenshot 2024-05-15 at 4 20 16 PM" src="https://github.com/bigcommerce/b2b-buyer-portal/assets/84735374/58d0ae7a-aa17-4a98-a83c-ca06c6216883">

**Comment by bc-victor** [comment]
We've seen this error before, can you continue developing after closing it?

**Comment by jp06** [comment]
I also saw this during development, I remember I just closed it also and it's still fine. I'm not sure if 3001 is alright to use with Buyer Portal if you're using port 3000 in Stencil as it might conflict with the non-browsersync port (unless that got assigned to a different port). I also had to tunnel the Stencil dev server due to CORS issues.
